stages:
  data_preparation:
    cmd: python data_preparation.py -id data/raw -od data/prepared
    deps:
      - data_preparation.py
      - data/raw
    outs:
      - data/prepared
    params:
      - data_preparation
  linear_regression:
    cmd: python liney_lineyich.py -id data/prepared -od data/models -mn ${linear_regression.model_name}
    deps:
      - liney_lineyich.py
      - data/prepared
    outs:
      - data/models/${linear_regression.model_name}.csv
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression

  linear_regression_validation:
    cmd: python liney_lineyich_invalid.py -id data/prepared/ -im data/models/${linear_regression.model_name}.joblib -mn ${linear_regression.model_name}
    deps:
      - liney_lineyich_invalid.py
      - data/prepared/
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression

  linear_regression_prod_version:
    cmd: python liney_lineyich_prod.py -id data/prepared/ -od data/models/ -mn ${linear_regression.model_name}
    deps:
      - liney_lineyich_prod.py
      - data/prepared
      - data/models/${linear_regression.model_name}.joblib
    outs:
      - data/models/${linear_regression.model_name}_prod.csv
      - data/models/${linear_regression.model_name}_prod.joblib
    params:
      - linear_regression
  decision_tree:
    foreach: ${decision_tree}
    do:
      cmd: python decision_derevo.py -id data/prepared -od data/models -bm data/models/${linear_regression.model_name}_prod.joblib -mn ${key} -p params.yaml
      deps:
        - decision_derevo.py
        - data/prepared
        - data/models/${linear_regression.model_name}_prod.joblib
      outs:
        - data/models/${key}.joblib
      params:
        - decision_tree
  decision_tree_validation:
    foreach: ${decision_tree}
    do:
      cmd: python decision_derevo_invalid.py -id data/prepared/ -im data/models/${key}.joblib -bm data/models/${linear_regression.model_name}_prod.joblib -mn ${key}
      deps:
        - decision_derevo_invalid.py
        - data/prepared/
        - data/models/${key}.joblib
        - data/models/${linear_regression.model_name}_prod.joblib
      params:
        - decision_tree
  decision_tree_prod:
    foreach: ${decision_tree}
    do:
      cmd: python decision_derevo_prod.py -id data/prepared/ -od data/models/ -mn ${key}
      deps:
        - decision_derevo_prod.py
        - data/prepared
        - data/models/${key}.joblib
      outs:
        - data/models/${key}_prod.joblib
      params:
        - decision_tree
  XGboosting:
    cmd: python OMGboosting.py -id data/prepared -od data/models -mn ${XGBoosting.model_name}
    deps:
      - OMGboosting.py
      - data/prepared
    outs:
      - data/models/${XGBoosting.model_name}.joblib
    params:
      - XGBoosting
  XGboosting_invalid:
    cmd: python OMGboosting_invalid.py -id data/prepared/ -im data/models/${XGBoosting.model_name}.joblib -mn ${XGBoosting.model_name}
    deps:
      - OMGboosting_invalid.py
      - data/prepared/
      - data/models/${XGBoosting.model_name}.joblib
    params:
      - XGBoosting
  XGboosting_prod:
    cmd: python OMGboosting_prod.py -id data/prepared -od data/models -mn ${XGBoosting.model_name}
    deps:
      - OMGboosting_prod.py
      - data/prepared
      - data/models/${XGBoosting.model_name}.joblib
    outs:
      - data/models/${XGBoosting.model_name}_prod.joblib
    params:
      - XGBoosting
  Cat:
    cmd: python koshka.py -id data/prepared -od data/models -mn ${Cat.model_name}
    deps:
      - koshka.py
      - data/prepared
    outs:
      - data/models/${Cat.model_name}.joblib
    params:
      - XGBoosting
  Cat_valid:
    cmd: python koshka_invalid.py -id data/prepared/ -im data/models/${Cat.model_name}.joblib -mn ${Cat.model_name}
    deps:
      - koshka_invalid.py
      - data/prepared/
      - data/models/${Cat.model_name}.joblib
    params:
      - Cat
  Cat_prod:
    cmd: python koshka_prod.py -id data/prepared -od data/models -mn ${Cat.model_name}
    deps:
      - koshka_prod.py
      - data/prepared
      - data/models/${Cat.model_name}.joblib
    outs:
      - data/models/${Cat.model_name}_prod.joblib
    params:
      - Cat

